version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    # network_mode: "host"
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        # mode: host
    user: "${UID}:${GID}"
    volumes:
      - type: bind
        source: .
        target: /usr/app
